import type { DatabaseSnapshot } from "./schema";

export const db: DatabaseSnapshot = {
  leagues: [
    {
      id: "league_nfl",
      slug: "national-franchise-league",
      name: "National Franchise League",
      logoSrc: "/league-logo.png",
      description: "The premier Madden franchise football experience.",
      platform: "PS5",
      season: 2026,
      week: 1,
      commissionerId: "pending_commissioner_setup",
      discordUrl: "https://discord.gg/nationalfranchiseleague",
      twitchChannel: "nationalfranchiseleague",
      youtubeChannelUrl: "https://www.youtube.com/@NFL.Madden25",
      instagramUrl: "https://www.instagram.com/nationalfranchiseleague/",
    },
  ],
  owners: [],
  teams: [
    { id: "ari", slug: "arizona-cardinals", leagueId: "league_nfl", city: "Arizona", name: "Cardinals", fullName: "Arizona Cardinals", abbreviation: "ARI", logoSrc: "/league-logo.png", primaryColor: "#97233F", secondaryColor: "#FFFFFF", isOpen: true },
    { id: "atl", slug: "atlanta-falcons", leagueId: "league_nfl", city: "Atlanta", name: "Falcons", fullName: "Atlanta Falcons", abbreviation: "ATL", logoSrc: "/league-logo.png", primaryColor: "#A71930", secondaryColor: "#000000", isOpen: true },
    { id: "bal", slug: "baltimore-ravens", leagueId: "league_nfl", city: "Baltimore", name: "Ravens", fullName: "Baltimore Ravens", abbreviation: "BAL", logoSrc: "/league-logo.png", primaryColor: "#241773", secondaryColor: "#9E7C0C", isOpen: true },
    { id: "buf", slug: "buffalo-bills", leagueId: "league_nfl", city: "Buffalo", name: "Bills", fullName: "Buffalo Bills", abbreviation: "BUF", logoSrc: "/teams/bills.png", primaryColor: "#00338D", secondaryColor: "#C60C30", isOpen: true },
    { id: "car", slug: "carolina-panthers", leagueId: "league_nfl", city: "Carolina", name: "Panthers", fullName: "Carolina Panthers", abbreviation: "CAR", logoSrc: "/league-logo.png", primaryColor: "#0085CA", secondaryColor: "#101820", isOpen: true },
    { id: "chi", slug: "chicago-bears", leagueId: "league_nfl", city: "Chicago", name: "Bears", fullName: "Chicago Bears", abbreviation: "CHI", logoSrc: "/league-logo.png", primaryColor: "#0B162A", secondaryColor: "#C83803", isOpen: true },
    { id: "cin", slug: "cincinnati-bengals", leagueId: "league_nfl", city: "Cincinnati", name: "Bengals", fullName: "Cincinnati Bengals", abbreviation: "CIN", logoSrc: "/league-logo.png", primaryColor: "#FB4F14", secondaryColor: "#000000", isOpen: true },
    { id: "cle", slug: "cleveland-browns", leagueId: "league_nfl", city: "Cleveland", name: "Browns", fullName: "Cleveland Browns", abbreviation: "CLE", logoSrc: "/league-logo.png", primaryColor: "#311D00", secondaryColor: "#FF3C00", isOpen: true },
    { id: "dal", slug: "dallas-cowboys", leagueId: "league_nfl", city: "Dallas", name: "Cowboys", fullName: "Dallas Cowboys", abbreviation: "DAL", logoSrc: "/teams/cowboys.png", primaryColor: "#BFC7D5", secondaryColor: "#0B1220", isOpen: true },
    { id: "den", slug: "denver-broncos", leagueId: "league_nfl", city: "Denver", name: "Broncos", fullName: "Denver Broncos", abbreviation: "DEN", logoSrc: "/league-logo.png", primaryColor: "#FB4F14", secondaryColor: "#002244", isOpen: true },
    { id: "det", slug: "detroit-lions", leagueId: "league_nfl", city: "Detroit", name: "Lions", fullName: "Detroit Lions", abbreviation: "DET", logoSrc: "/league-logo.png", primaryColor: "#0076B6", secondaryColor: "#B0B7BC", isOpen: true },
    { id: "gb", slug: "green-bay-packers", leagueId: "league_nfl", city: "Green Bay", name: "Packers", fullName: "Green Bay Packers", abbreviation: "GB", logoSrc: "/league-logo.png", primaryColor: "#203731", secondaryColor: "#FFB612", isOpen: true },
    { id: "hou", slug: "houston-texans", leagueId: "league_nfl", city: "Houston", name: "Texans", fullName: "Houston Texans", abbreviation: "HOU", logoSrc: "/league-logo.png", primaryColor: "#03202F", secondaryColor: "#A71930", isOpen: true },
    { id: "ind", slug: "indianapolis-colts", leagueId: "league_nfl", city: "Indianapolis", name: "Colts", fullName: "Indianapolis Colts", abbreviation: "IND", logoSrc: "/league-logo.png", primaryColor: "#002C5F", secondaryColor: "#A2AAAD", isOpen: true },
    { id: "jax", slug: "jacksonville-jaguars", leagueId: "league_nfl", city: "Jacksonville", name: "Jaguars", fullName: "Jacksonville Jaguars", abbreviation: "JAX", logoSrc: "/league-logo.png", primaryColor: "#006778", secondaryColor: "#D7A22A", isOpen: true },
    { id: "kc", slug: "kansas-city-chiefs", leagueId: "league_nfl", city: "Kansas City", name: "Chiefs", fullName: "Kansas City Chiefs", abbreviation: "KC", logoSrc: "/teams/chiefs.png", primaryColor: "#E31837", secondaryColor: "#FFFFFF", isOpen: true },
    { id: "lv", slug: "las-vegas-raiders", leagueId: "league_nfl", city: "Las Vegas", name: "Raiders", fullName: "Las Vegas Raiders", abbreviation: "LV", logoSrc: "/teams/raiders.png", primaryColor: "#A5ACAF", secondaryColor: "#000000", isOpen: true },
    { id: "lac", slug: "los-angeles-chargers", leagueId: "league_nfl", city: "Los Angeles", name: "Chargers", fullName: "Los Angeles Chargers", abbreviation: "LAC", logoSrc: "/league-logo.png", primaryColor: "#0080C6", secondaryColor: "#FFC20E", isOpen: true },
    { id: "lar", slug: "los-angeles-rams", leagueId: "league_nfl", city: "Los Angeles", name: "Rams", fullName: "Los Angeles Rams", abbreviation: "LAR", logoSrc: "/league-logo.png", primaryColor: "#003594", secondaryColor: "#FFA300", isOpen: true },
    { id: "mia", slug: "miami-dolphins", leagueId: "league_nfl", city: "Miami", name: "Dolphins", fullName: "Miami Dolphins", abbreviation: "MIA", logoSrc: "/teams/dolphins.png", primaryColor: "#008E97", secondaryColor: "#FC4C02", isOpen: true },
    { id: "min", slug: "minnesota-vikings", leagueId: "league_nfl", city: "Minnesota", name: "Vikings", fullName: "Minnesota Vikings", abbreviation: "MIN", logoSrc: "/league-logo.png", primaryColor: "#4F2683", secondaryColor: "#FFC62F", isOpen: true },
    { id: "ne", slug: "new-england-patriots", leagueId: "league_nfl", city: "New England", name: "Patriots", fullName: "New England Patriots", abbreviation: "NE", logoSrc: "/league-logo.png", primaryColor: "#002244", secondaryColor: "#C60C30", isOpen: true },
    { id: "no", slug: "new-orleans-saints", leagueId: "league_nfl", city: "New Orleans", name: "Saints", fullName: "New Orleans Saints", abbreviation: "NO", logoSrc: "/league-logo.png", primaryColor: "#D3BC8D", secondaryColor: "#101820", isOpen: true },
    { id: "nyg", slug: "new-york-giants", leagueId: "league_nfl", city: "New York", name: "Giants", fullName: "New York Giants", abbreviation: "NYG", logoSrc: "/teams/giants.png", primaryColor: "#0B5CFF", secondaryColor: "#FFFFFF", isOpen: true },
    { id: "nyj", slug: "new-york-jets", leagueId: "league_nfl", city: "New York", name: "Jets", fullName: "New York Jets", abbreviation: "NYJ", logoSrc: "/league-logo.png", primaryColor: "#125740", secondaryColor: "#FFFFFF", isOpen: true },
    { id: "phi", slug: "philadelphia-eagles", leagueId: "league_nfl", city: "Philadelphia", name: "Eagles", fullName: "Philadelphia Eagles", abbreviation: "PHI", logoSrc: "/teams/eagles.png", primaryColor: "#0B6B57", secondaryColor: "#00A3FF", isOpen: true },
    { id: "pit", slug: "pittsburgh-steelers", leagueId: "league_nfl", city: "Pittsburgh", name: "Steelers", fullName: "Pittsburgh Steelers", abbreviation: "PIT", logoSrc: "/league-logo.png", primaryColor: "#FFB612", secondaryColor: "#101820", isOpen: true },
    { id: "sf", slug: "san-francisco-49ers", leagueId: "league_nfl", city: "San Francisco", name: "49ers", fullName: "San Francisco 49ers", abbreviation: "SF", logoSrc: "/league-logo.png", primaryColor: "#AA0000", secondaryColor: "#B3995D", isOpen: true },
    { id: "sea", slug: "seattle-seahawks", leagueId: "league_nfl", city: "Seattle", name: "Seahawks", fullName: "Seattle Seahawks", abbreviation: "SEA", logoSrc: "/league-logo.png", primaryColor: "#002244", secondaryColor: "#69BE28", isOpen: true },
    { id: "tb", slug: "tampa-bay-buccaneers", leagueId: "league_nfl", city: "Tampa Bay", name: "Buccaneers", fullName: "Tampa Bay Buccaneers", abbreviation: "TB", logoSrc: "/league-logo.png", primaryColor: "#D50A0A", secondaryColor: "#FF7900", isOpen: true },
    { id: "ten", slug: "tennessee-titans", leagueId: "league_nfl", city: "Tennessee", name: "Titans", fullName: "Tennessee Titans", abbreviation: "TEN", logoSrc: "/league-logo.png", primaryColor: "#0C2340", secondaryColor: "#4B92DB", isOpen: true },
    { id: "was", slug: "washington-commanders", leagueId: "league_nfl", city: "Washington", name: "Commanders", fullName: "Washington Commanders", abbreviation: "WAS", logoSrc: "/teams/commanders.png", primaryColor: "#8A1538", secondaryColor: "#FFB612", isOpen: true },
  ],
  ownerAchievements: [
    { id: "founding-member", label: "Founding Member", description: "Joined during the launch season." },
    { id: "commissioner", label: "Commissioner", description: "Assigned league commissioner responsibilities." },
    { id: "league-veteran", label: "League Veteran", description: "Recognized for long-term league participation." },
    { id: "reliable-owner", label: "Reliable Owner", description: "Consistent scheduling, communication, and game completion." },
    { id: "broadcaster", label: "Broadcaster", description: "Regularly streams league games." },
    { id: "good-sportsmanship", label: "Good Sportsmanship", description: "Recognized for respectful competitive conduct." },
    { id: "division-champion", label: "Division Champion", description: "Won a National Franchise League division title." },
    { id: "conference-champion", label: "Conference Champion", description: "Won a conference championship." },
    { id: "super-bowl-champion", label: "Super Bowl Champion", description: "Won the National Franchise League Super Bowl." },
    { id: "ironman", label: "Ironman", description: "Completed a full season with excellent availability." },
    { id: "dynasty", label: "Dynasty", description: "Sustained championship-level performance across seasons." },
    { id: "hall-of-fame", label: "Hall of Fame", description: "Recognized as a Hall of Fame owner." },
  ],
  applications: [],
  ownerMemberships: [],
  ownerTeamAssignments: [],
  ownerSeasonHistory: [],
  teamLotteryEntries: [],
  teamLotterySelections: [],
  games: [
    { id: "game_1", leagueId: "league_nfl", week: 1, awayTeamId: "dal", homeTeamId: "nyg", status: "scheduled", kickoffAt: "2026-07-08T20:00:00-04:00", streamUrl: "https://www.twitch.tv/nationalfranchiseleague", isGameOfTheWeek: true },
    { id: "game_2", leagueId: "league_nfl", week: 1, awayTeamId: "phi", homeTeamId: "was", awayScore: 31, homeScore: 28, status: "final", kickoffAt: "2026-07-04T19:30:00-04:00" },
    { id: "game_3", leagueId: "league_nfl", week: 1, awayTeamId: "buf", homeTeamId: "mia", awayScore: 24, homeScore: 17, status: "final", kickoffAt: "2026-07-05T21:15:00-04:00" },
    { id: "game_4", leagueId: "league_nfl", week: 1, awayTeamId: "kc", homeTeamId: "lv", awayScore: 35, homeScore: 34, status: "final", kickoffAt: "2026-07-05T22:00:00-04:00" },
    { id: "game_5", leagueId: "league_nfl", week: 1, awayTeamId: "was", homeTeamId: "nyg", status: "scheduled", kickoffAt: "2026-07-09T19:00:00-04:00" },
  ],
  standings: [
    { id: "st_1", leagueId: "league_nfl", teamId: "nyg", wins: 7, losses: 1, ties: 0, pointsFor: 246, pointsAgainst: 160 },
    { id: "st_2", leagueId: "league_nfl", teamId: "dal", wins: 6, losses: 2, ties: 0, pointsFor: 231, pointsAgainst: 177 },
    { id: "st_3", leagueId: "league_nfl", teamId: "phi", wins: 6, losses: 2, ties: 0, pointsFor: 214, pointsAgainst: 183 },
    { id: "st_4", leagueId: "league_nfl", teamId: "was", wins: 5, losses: 3, ties: 0, pointsFor: 198, pointsAgainst: 180 },
    { id: "st_5", leagueId: "league_nfl", teamId: "kc", wins: 5, losses: 3, ties: 0, pointsFor: 220, pointsAgainst: 206 },
    { id: "st_6", leagueId: "league_nfl", teamId: "buf", wins: 5, losses: 3, ties: 0, pointsFor: 203, pointsAgainst: 194 },
    { id: "st_7", leagueId: "league_nfl", teamId: "lv", wins: 4, losses: 4, ties: 0, pointsFor: 187, pointsAgainst: 189 },
    { id: "st_8", leagueId: "league_nfl", teamId: "mia", wins: 4, losses: 4, ties: 0, pointsFor: 192, pointsAgainst: 203 },
  ],
  trades: [
    { id: "trade_1", leagueId: "league_nfl", fromTeamId: "dal", toTeamId: "was", summary: "Dallas submitted a 2027 2nd-round pick package for secondary help.", status: "pending", submittedAt: "2026-07-06T12:00:00-04:00" },
  ],
  announcements: [
    { id: "ann_1", leagueId: "league_nfl", title: "Week 1 advance", body: "Advance window closes Wednesday at 9 PM ET.", createdAt: "2026-07-06T09:00:00-04:00" },
    { id: "ann_2", leagueId: "league_nfl", title: "Trade approvals", body: "Both owners must confirm accepted trades in Discord before committee review.", createdAt: "2026-07-06T10:00:00-04:00" },
  ],
  rules: [
    { id: "rule_1", leagueId: "league_nfl", title: "League Settings", order: 1, body: ["All-Madden.", "7-minute quarters.", "Play cooldown 5.", "Play limit 4."] },
    { id: "rule_2", leagueId: "league_nfl", title: "Advance Schedule", order: 2, body: ["Advance days are Wednesday and Sunday.", "Advance window is 3-5 PM EST."] },
  ],
  hallOfFame: [
    { id: "hof_1", leagueId: "league_nfl", category: "Champions", title: "Champions", description: "Premium Madden franchise history under the National Franchise League umbrella." },
    { id: "hof_2", leagueId: "league_nfl", category: "Awards", title: "Award Winners", description: "Season awards, MVPs, and owner achievements." },
    { id: "hof_3", leagueId: "league_nfl", category: "Records", title: "Record Breakers", description: "League records and historic performances." },
  ],
  awards: [
    { id: "award_1", leagueId: "league_nfl", season: 2026, week: 1, title: "Game of the Week", winner: "New York Giants vs Dallas Cowboys", teamId: "nyg" },
  ],
  stats: [
    { id: "stat_1", leagueId: "league_nfl", teamId: "buf", playerName: "Josh Allen", category: "Passing", value: "2,418 YDS", extra: "28 TD" },
    { id: "stat_2", leagueId: "league_nfl", teamId: "phi", playerName: "Saquon Barkley", category: "Rushing", value: "1,126 YDS", extra: "14 TD" },
    { id: "stat_3", leagueId: "league_nfl", teamId: "mia", playerName: "Tyreek Hill", category: "Receiving", value: "982 YDS", extra: "11 TD" },
    { id: "stat_4", leagueId: "league_nfl", teamId: "dal", playerName: "Micah Parsons", category: "Sacks", value: "13.5", extra: "4 FF" },
    { id: "stat_5", leagueId: "league_nfl", teamId: "nyg", playerName: "Sauce Gardner", category: "INTs", value: "7", extra: "2 TD" },
    { id: "stat_6", leagueId: "league_nfl", teamId: "was", playerName: "Bobby Wagner", category: "Tackles", value: "72", extra: "9 TFL" },
    { id: "stat_7", leagueId: "league_nfl", teamId: "dal", playerName: "DaRon Bland", category: "Def TD", value: "3", extra: "6 INT" },
  ],
  powerRankings: [
    { id: "pr_1", leagueId: "league_nfl", teamId: "nyg", rank: 1, note: "Balanced, ruthless, and playing like a top Madden user team." },
    { id: "pr_2", leagueId: "league_nfl", teamId: "dal", rank: 2, note: "Explosive offense with a broadcast-game ceiling." },
    { id: "pr_3", leagueId: "league_nfl", teamId: "phi", rank: 3, note: "Defense and run game are built for playoff Madden." },
    { id: "pr_4", leagueId: "league_nfl", teamId: "kc", rank: 4, note: "Passing attack can flip any game in one drive." },
    { id: "pr_5", leagueId: "league_nfl", teamId: "buf", rank: 5, note: "One statement win from a power rankings jump." },
  ],
  transactions: [
    { id: "tx_1", leagueId: "league_nfl", teamId: "nyg", description: "Signed WR depth to the active roster.", createdAt: "2026-07-06T11:00:00-04:00" },
    { id: "tx_2", leagueId: "league_nfl", teamId: "dal", description: "Traded a 2027 2nd-round pick for secondary help.", createdAt: "2026-07-06T11:15:00-04:00" },
    { id: "tx_3", leagueId: "league_nfl", teamId: "phi", description: "Placed starting HB on short-term IR.", createdAt: "2026-07-06T11:30:00-04:00" },
    { id: "tx_4", leagueId: "league_nfl", teamId: "was", description: "Activated rookie linebacker before rivalry week.", createdAt: "2026-07-06T11:45:00-04:00" },
  ],
};
