import {
  BookOpen,
  CalendarDays,
  ClipboardList,
  Gamepad2,
  Gavel,
  HelpCircle,
  Radio,
  Scale,
  ShieldCheck,
  Trophy,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type RulebookRule = {
  title: string;
  summary: string;
  content: string[];
};

export type RulebookCategory = {
  title: string;
  summary: string;
  icon: LucideIcon;
  rules: RulebookRule[];
};

export const rulebookMeta = {
  version: "v1.0 Official Review",
  lastUpdated: "July 27, 2026",
  sourceStatus: "Official rulebook content is embedded in the National Franchise League website for commissioner review before production.",
};

export const whatsNew = [
  {
    title: "Full Rulebook Migration",
    date: "July 27, 2026",
    note: "Current league rules were imported into the website as the permanent official digital rulebook home.",
  },
  {
    title: "Future Changes",
    date: "Next approved update",
    note: "Commissioner-approved rule changes can be added here with a date, version, and summary.",
  },
];

export const newOwnerGuide = [
  {
    title: "Set Up Before You Play",
    body: "Owners play on PlayStation 5 with crossplay enabled, Simulation game style, All-Madden difficulty, 7-minute quarters, 20-second accelerated clock, and the published play cooldown and play call limits.",
  },
  {
    title: "Communicate Early",
    body: "GroupMe is the official hub for scheduling, trades, and announcements. Owners have a 10-hour response window when contacted, and communication logs are reviewed by commissioners.",
  },
  {
    title: "Finish Every Game",
    body: "If you start a game, you must finish it. Legitimate disconnects, console crashes, and real-life emergencies must be communicated immediately.",
  },
  {
    title: "Stream Featured Games",
    body: "All Games of the Week and Playoff Games must be streamed on YouTube or Twitch. Game of the Week selections rotate across AFC and NFC matchups.",
  },
  {
    title: "Play Real Football",
    body: "Gameplay should emulate real NFL football. Avoid exploit mechanics, unrealistic substitutions, nanos, manual gap stacking, no-huddle abuse, and QB drift or dropback abuse.",
  },
];

export const rulebookCategories: RulebookCategory[] = [
  {
    title: "Getting Started",
    summary: "League identity, setup, platforms, and launch expectations.",
    icon: BookOpen,
    rules: [
      {
        title: "Realistic Competition. Integrity. Flexibility for Busy Players.",
        summary: "The league standard and guiding purpose for every owner.",
        content: [
          "Realistic Competition. Integrity. Flexibility for Busy Players.",
          "🏆 National Franchise League (NFL)",
          "Official Rulebook",
          "Commissioner’s Preamble",
          "The National Franchise League (NFL) was founded to redefine the Madden experience — built upon realism, integrity, and competition.",
          "This league stands for more than just games played. It represents discipline, football IQ, and respect for the sport. Each rule within this document was crafted to ensure balance, fairness, and authentic NFL gameplay.",
          "When you step onto the field, you represent a standard — a community of players who respect the grind, honor the game, and compete the right way.",
          "🏈 Welcome to the National Franchise League — Built for the Real Ones.",
        ],
      },
      {
        title: "⚙️ Part 1 — League Setup & Schedule",
        summary: "Core league setup and required Madden franchise settings.",
        content: [
          "⚙️ Part 1 — League Setup & Schedule",
          "The foundation of the league is structure and fairness. Every setting ensures a level playing field for every owner.",
          "🎮 League Configuration:",
          "Platform: 🕹️ PlayStation 5 (Crossplay Enabled)",
          "Game Style: Simulation",
          "Difficulty: All-Madden",
          "Quarter Length: 7 Minutes",
          "Accelerated Clock: On (20s)",
          "Injuries: On ",
          "Fatigue: On ",
          "Progressive Fatigue: On",
          "Weather: Live (Real-World Conditions)",
          "Play Cooldown: 5 Plays ",
          "Play Call Limit: 4 Plays",
          "Practice Squad Stealing: Enabled (Begins Week 3)",
          "Pre-Game Pause: Up to 5 Minutes for roster adjustments",
          "Uniform Policy: One light + one dark uniform",
          "Advance Days: 🗓️ Monday, Wednesday & fridays between 5-6pm ",
          "⚖️ League settings mirror real football — balance, realism, and integrity above all.",
        ],
      },
      {
        title: "💬 Part 4 - Communication",
        summary: "Official communication channels for scheduling, trades, media, and announcements.",
        content: [
          "💬 Part 4 - Communication",
          "Communication ensures consistency and order throughout the league.",
          "📱 League Platforms:",
          "GroupMe — official hub for scheduling, trades, and announcements.",
          "Instagram (@nfl.madden25) — for highlights, awards, and media.",
          "💡 If it’s league-related — it’s on GroupMe.",
        ],
      },
    ],
  },
  {
    title: "Gameplay Rules",
    summary: "On-field conduct, realistic play requirements, and exploit prevention.",
    icon: Gamepad2,
    rules: [
      {
        title: "📖 Part 2 — No Quitting Policy",
        summary: "Owners must complete games once they start.",
        content: [
          "📖 Part 2 — No Quitting Policy",
          "Commitment defines integrity. Quitting or conceding is a direct violation of league conduct.",
          "🚫 No Quitting or Conceding:",
          "If you start a game, you must finish it. Rage quits or dashboarding are not tolerated.",
          "✅ Exceptions:",
          "Legitimate disconnects or console crashes",
          "Real-life emergencies (must notify a commissioner immediately)",
          "⚖️ Penalties:",
          "1st Infraction — 3-Game QB Suspension",
          "2nd Infraction — Removal from League",
          "🏈 If you start it — you finish it.",
        ],
      },
      {
        title: "⏸️ Part 5 — Pause & In-Game Communication",
        summary: "Pauses are allowed for communication and personal needs, not strategy.",
        content: [
          "⏸️ Part 5 — Pause & In-Game Communication",
          "Pauses are a courtesy, not a strategy.",
          "🕹️ Pause Rules:",
          "Allowed for rule alerts or personal reasons.",
          "Communicate clearly when pausing.",
          "Limit: 5 minutes max unless approved.",
          "Excessive or unannounced pauses = strike or penalty.",
          "💬 Transparency builds trust.",
        ],
      },
      {
        title: "🧠 Part 11 — Gameplay Conduct",
        summary: "Real NFL football standards and mechanic-abuse limits.",
        content: [
          "🧠 Part 11 — Gameplay Conduct",
          "Gameplay should emulate real NFL football — not exploit mechanics.",
          "🏃‍♂️ Motion Rule:",
          "No hiking during motion unless play design permits.",
          "⚡ Speed Burst Rule:",
          "No hand-switching or animation exploits.",
          "🎯 QB Play:",
          "Max dropback: 10 yds (under center), 8 yds (shotgun).",
          "No backward running or drift abuse.",
          "🚨 No Huddle Rule:",
          "Once per drive unless in 2-min or comeback mode.",
        ],
      },
      {
        title: "🛡️ Part 12 — Defense, Goal Line, & 4th Down Rules",
        summary: "Defensive standards, goal line limits, fourth-down policy, and penalties.",
        content: [
          "🛡️ Part 12 — Defense, Goal Line, & 4th Down Rules",
          "Defense wins championships — but only within the rules.",
          "🧱 Defensive Rules:",
          "Minimum 3 rushers (inside tackle box).",
          "No nanos, exploit blitzes, or looping with 3-man rush.",
          "No manual stacking of safeties/LBs to force gaps.",
          "Match personnel — Base vs <3WR; Nickel/Dime vs 3+.",
          "🏈 Goal Line Rules:",
          "Only inside 10-yard line.",
          "Outside 10 — jumbo/short-yardage sets only.",
          "🚦 4th Down Policy:",
          "Inside opponent’s 40 → 4th & 2 or less allowed.",
          "Losing by 14+ → may go for it anywhere.",
          "Inside the half way point  (4th Q) 4 minute mark → free to go for win/tie/cut lead.  up by 9 or more then you must punt, if you’re up by 8 you may go for it ",
          "🎯 2PT Conversions:",
          "Allowed when needed to tie or win.",
          "Losing teams may attempt anytime.",
          "🚨 Penalties:",
          "1st — 1 Suspension",
          "2nd — 5 Suspensions (3 DEF / 2 OFF)",
          "3rd — –3 SPD reduction on starter.",
        ],
      },
      {
        title: "🤖 Part 7 — CPU Games & Stat Caps",
        summary: "CPU games have stat limits and penalties for cap violations.",
        content: [
          "🤖 Part 7 — CPU Games & Stat Caps",
          "CPU games are for progress, not exploitation.",
          "📊 Limits:",
          "QB — 400 Yards Max",
          "RB — 250 Yards Max",
          "WR/TE — 250 Yards Max",
          "Max 5 CPU attempts ",
          "⚠️ Violations:",
          "Exceeding caps results in a 5 AWR deduction or suspension for involved players.",
        ],
      },
    ],
  },
  {
    title: "Scheduling",
    summary: "Advance timing, response windows, force wins, and sim outcomes.",
    icon: CalendarDays,
    rules: [
      {
        title: "🕒 Scheduling & Sim Policy",
        summary: "Owners must communicate before advance and respond inside the scheduling window.",
        content: [
          "🕒 Scheduling & Sim Policy",
          "📅 Advance Expectations:",
          "Advances occur promptly between 5-6 PM EST.",
          "All games must be played, scheduled, or communicated before advance.",
          "⚡ Scheduling Window:",
          "Owners have a 10-hour window to respond when contacted.",
          "Failure to respond = potential Force Win (FW) for the active owner (proof required).",
          "🎲 Sim Policy:",
          "No response from either owner = game goes to the Sim Gods (random result).",
          "Commissioners review all cases using communication logs.",
          "💡 Respect the schedule. Communicate clearly. Protect your season.",
        ],
      },
    ],
  },
  {
    title: "Streaming",
    summary: "Streaming requirements, Games of the Week, rewards, and media highlights.",
    icon: Radio,
    rules: [
      {
        title: "📺 Part 6 — Streaming & Game of the Week",
        summary: "Featured games and playoffs must be streamed, with Game of the Week rewards available.",
        content: [
          "📺 Part 6 — Streaming & Game of the Week",
          "Visibility strengthens integrity. Streams validate gameplay and showcase talent.",
          "🎥 Mandatory Streaming:",
          "All Games of the Week and Playoff Games must be streamed.",
          "Approved platforms: YouTube or Twitch.",
          "Players are encouraged to use consistent team-named channels when possible for easy access.",
          "🏆Game of the Week Format",
          "To boost competition and division pride, the league features 4 Games of the Week every advance — 2 AFC and 2 NFC matchups.",
          "All Games of the Week must be streamed on YouTube/Twitch ",
          "📋 Structure:",
          "Commissioners select 4 inter-divisional matchups each advance.",
          "Selections rotate so every team is featured fairly throughout the season.",
          "🔥 Game of the Week Rewards:",
          "Winners: +2 Attribute Points (<80 OVR)",
          "Division members of the winner: +1 Attribute Point (<80 OVR)",
          "No rewards for SIM or FW games",
          "🏁 Attribute Policy:",
          "Attribute cap: 85 OVR",
          "No SPD, ACC, THP, THA, STR, or PRC boosts",
          "Must post results before advance",
          "🏅 Season Bonus Incentives:",
          "Owners who play 13 or more total games may upgrade one Normal dev player to Star.",
          "The Super Bowl Champion may upgrade one rookie they drafted to Star.",
          "📸 League Media & Highlights:",
          "Players are encouraged to send highlight clips, game-winning plays, or cinematic moments to the Commissioner Team.",
          "Submitted clips may be featured on the official Instagram page — @nfl.madden25 or league highlights feed.",
          "⚖️ Consistency and championship effort are rewarded — not shortcuts.",
        ],
      },
    ],
  },
  {
    title: "Trades",
    summary: "Committee approval, trade limits, anti-collusion, and salary-cap movement.",
    icon: Scale,
    rules: [
      {
        title: "💰 Part 8 — Salary Cap & Trading Rules",
        summary: "Salary cap movement and trades must follow committee rules.",
        content: [
          "💰 Part 8 — Salary Cap & Trading Rules",
          "Team management is an art. Rules ensure fair, realistic roster movement.",
          "💰 Salary Cap:",
          "No cutting and re-signing same player.",
          "Player must remain FA until next advance.",
          "Penalty: Player loss + QB –10 AWR.",
          "💼 Trading Rules:",
          "All trades posted in GroupMe and approved by Trade Committee.",
          "No CPU trades.",
          "Both owners must “like” post before approval.",
          "Limit: 6 trades per season (3 Offseason + 3 Regular).",
          "Anti-Collusion: No trades between recruiter and recruit for 2 full seasons.",
        ],
      },
    ],
  },
  {
    title: "Team Management",
    summary: "Team lottery, free agency, illegal substitutions, roster minimums, and editing.",
    icon: ClipboardList,
    rules: [
      {
        title: "🧾 Part 9 — Team Lottery & Free Agency System",
        summary: "Team selection and preseason free agency are structured for competitive balance.",
        content: [
          "🧾 Part 9 — Team Lottery & Free Agency System",
          "Competitive balance begins before kickoff.",
          "🎲 Team Lottery (Season 1):",
          "Randomized order determines team selection.",
          "Announced publicly before launch.",
          "💼 Preseason FA Draft:",
          "Week 1 — Reverse of lottery = FA order.",
          "Weeks 2–3 — First-come, first-serve; 2 signings max (1 offense, 1 defense).",
          "After Week 3 — Free agency opens to all.",
          "⚖️ Fair starts lead to fair competition.",
        ],
      },
      {
        title: "🧩 Part 10 — Illegal Subs / Roster Rules / Editing",
        summary: "Rosters must match true NFL structure and league position standards.",
        content: [
          "🧩 Part 10 — Illegal Subs / Roster Rules / Editing",
          "Rosters must reflect true NFL structure and positions.",
          "⚙️ Illegal Subs:",
          "Offense: ❌ WR→HB/TE | OL→FB/TE",
          "Defense: ❌ SS/FS→CB/LB | CB→SS/FS",
          "Penalty: Strike or removal.",
          "📋 Roster Rules:",
          "42–53 players required",
          "FB optional",
          "Must meet minimums by Week 1",
          "✏️ Editing Policy:",
          "Only allowed in offseason.",
          "Rerolling XP/abilities = dev demotion or game loss.",
        ],
      },
    ],
  },
  {
    title: "Sportsmanship",
    summary: "Owner conduct, respect, recruiting, and league culture.",
    icon: Users,
    rules: [
      {
        title: "\n💪 Part 3 -Sportsmanship & Conduct",
        summary: "Competitive energy is welcome; personal attacks are not.",
        content: [
          "\n💪 Part 3 -Sportsmanship & Conduct",
          "Competition drives the league — respect sustains it.",
          "🔥 Code of Conduct:",
          "Trash talk is allowed — it fuels competition.",
          "Personal insults, harassment, or toxicity are not tolerated.",
          "Keep it competitive, not personal.",
          "Respect every opponent, every game.",
          "🏈 Win with class. Lose with dignity.",
        ],
      },
      {
        title: "🤝 League Recruiting:",
        summary: "Potential members should match the league’s culture and competitive standard.",
        content: [
          "🤝 League Recruiting:",
          "If you know someone who embodies the values of this league — sportsmanship, discipline, and realism — you are welcome to refer them to the commissioner team for consideration.",
          "Every potential member will be reviewed to ensure they align with the league’s culture and competitive standards.",
          "If a candidate is not selected, please understand — this league maintains a specific vision and style of play, and it’s not for everyone.",
          "⚡ Quality over quantity. The right players make the right league.",
          "🏁 Play smart. Play fair. Have fun.",
        ],
      },
    ],
  },
  {
    title: "Commissioner Authority",
    summary: "Enforcement, strike system, commission team, and documented review.",
    icon: Gavel,
    rules: [
      {
        title: "⚖️ Part 14 — League Enforcement (3-Strike System)",
        summary: "Violations are documented and enforced by the commissioner team.",
        content: [
          "⚖️ Part 14 — League Enforcement (3-Strike System)",
          "Accountability maintains order.",
          "1️⃣ 1st Strike: Warning or 1-Game Suspension",
          "2️⃣ 2nd Strike: 5 Suspensions (3 DEF / 2 OFF)",
          "3️⃣ 3rd Strike: Attribute Reduction (–3 SPD or equivalent)",
          "After 3 strikes, owner review or removal may occur.",
          "All violations documented by commissioners.",
          "✅ Commission Team",
          "Head Commissioner: Fuegobravo",
          "Co-Commissioner: Doughstax",
          "Trade Committee: Onthemaybach + Kadafijones1 ",
          "🩵 Final Message:",
          "This league is for players who respect the game, study their craft, and compete with integrity.",
          "Represent your team, play the right way, and honor the National Franchise League standard.",
        ],
      },
    ],
  },
  {
    title: "Playoffs",
    summary: "Playoff streaming rotation and playoff disconnect approval.",
    icon: Trophy,
    rules: [
      {
        title: "🏟️ Playoff Streaming Rotation:",
        summary: "Each playoff round has a designated streaming responsibility.",
        content: [
          "🏟️ Playoff Streaming Rotation:",
          "Wild Card — Away Team",
          "Divisional — Home Team",
          "Conference — Away Team",
          "Super Bowl — Home Team",
        ],
      },
      {
        title: "Playoff Disconnects",
        summary: "Playoff disconnects require commissioner approval before restart.",
        content: ["Playoff disconnects require commissioner approval before restart."],
      },
    ],
  },
  {
    title: "League Policies",
    summary: "Disconnects, policy reminders, penalties, and league-wide standards.",
    icon: ShieldCheck,
    rules: [
      {
        title: "⚡ Part 13-Disconnections",
        summary: "Disconnects require immediate communication and commissioner oversight when needed.",
        content: [
          "⚡ Part 13-Disconnections",
          "Technical issues happen — sportsmanship must not.",
          "Communicate immediately after disconnects.",
          "Recreate score/time or restart if agreed.",
          "Opponent quits/unplugs → screenshot & send to commissioner.",
          "Playoff disconnects require commissioner approval before restart.",
        ],
      },
      {
        title: "League Standards",
        summary: "Core reminders from the rulebook’s final message.",
        content: [
          "This league is for players who respect the game, study their craft, and compete with integrity.",
          "Represent your team, play the right way, and honor the National Franchise League standard.",
        ],
      },
    ],
  },
  {
    title: "FAQ",
    summary: "Fast answers for common owner questions using official rulebook text.",
    icon: HelpCircle,
    rules: [
      {
        title: "Where do owners communicate?",
        summary: "GroupMe is the official league hub.",
        content: [
          "GroupMe — official hub for scheduling, trades, and announcements.",
          "💡 If it’s league-related — it’s on GroupMe.",
        ],
      },
      {
        title: "When does the league advance?",
        summary: "Advance timing is listed in the league setup and scheduling policy.",
        content: [
          "Advance Days: 🗓️ Monday, Wednesday & fridays between 5-6pm ",
          "Advances occur promptly between 5-6 PM EST.",
        ],
      },
      {
        title: "What happens if someone does not respond?",
        summary: "The rulebook defines a 10-hour response window and commissioner review process.",
        content: [
          "Owners have a 10-hour window to respond when contacted.",
          "Failure to respond = potential Force Win (FW) for the active owner (proof required).",
          "No response from either owner = game goes to the Sim Gods (random result).",
          "Commissioners review all cases using communication logs.",
        ],
      },
      {
        title: "Which games must be streamed?",
        summary: "Featured and playoff games have mandatory streaming requirements.",
        content: [
          "All Games of the Week and Playoff Games must be streamed.",
          "Approved platforms: YouTube or Twitch.",
          "All Games of the Week must be streamed on YouTube/Twitch ",
        ],
      },
    ],
  },
];

export const rulebookQuickStats = [
  ["Version", rulebookMeta.version],
  ["Updated", rulebookMeta.lastUpdated],
  ["Categories", String(rulebookCategories.length)],
  ["Official Home", "NFL Website"],
];

export const originalNotionStatements = [
  "Realistic Competition. Integrity. Flexibility for Busy Players.",
  "🏆 National Franchise League (NFL)",
  "Official Rulebook",
  "Commissioner’s Preamble",
  "The National Franchise League (NFL) was founded to redefine the Madden experience — built upon realism, integrity, and competition.",
  "This league stands for more than just games played. It represents discipline, football IQ, and respect for the sport. Each rule within this document was crafted to ensure balance, fairness, and authentic NFL gameplay.",
  "When you step onto the field, you represent a standard — a community of players who respect the grind, honor the game, and compete the right way.",
  "🏈 Welcome to the National Franchise League — Built for the Real Ones.",
  "⚙️ Part 1 — League Setup & Schedule",
  "The foundation of the league is structure and fairness. Every setting ensures a level playing field for every owner.",
  "🎮 League Configuration:",
  "Platform: 🕹️ PlayStation 5 (Crossplay Enabled)",
  "Game Style: Simulation",
  "Difficulty: All-Madden",
  "Quarter Length: 7 Minutes",
  "Accelerated Clock: On (20s)",
  "Injuries: On ",
  "Fatigue: On ",
  "Progressive Fatigue: On",
  "Weather: Live (Real-World Conditions)",
  "Play Cooldown: 5 Plays ",
  "Play Call Limit: 4 Plays",
  "Practice Squad Stealing: Enabled (Begins Week 3)",
  "Pre-Game Pause: Up to 5 Minutes for roster adjustments",
  "Uniform Policy: One light + one dark uniform",
  "Advance Days: 🗓️ Monday, Wednesday & fridays between 5-6pm ",
  "⚖️ League settings mirror real football — balance, realism, and integrity above all.",
  "🕒 Scheduling & Sim Policy",
  "📅 Advance Expectations:",
  "Advances occur promptly between 5-6 PM EST.",
  "All games must be played, scheduled, or communicated before advance.",
  "⚡ Scheduling Window:",
  "Owners have a 10-hour window to respond when contacted.",
  "Failure to respond = potential Force Win (FW) for the active owner (proof required).",
  "🎲 Sim Policy:",
  "No response from either owner = game goes to the Sim Gods (random result).",
  "Commissioners review all cases using communication logs.",
  "💡 Respect the schedule. Communicate clearly. Protect your season.",
  "📖 Part 2 — No Quitting Policy",
  "Commitment defines integrity. Quitting or conceding is a direct violation of league conduct.",
  "🚫 No Quitting or Conceding:",
  "If you start a game, you must finish it. Rage quits or dashboarding are not tolerated.",
  "✅ Exceptions:",
  "Legitimate disconnects or console crashes",
  "Real-life emergencies (must notify a commissioner immediately)",
  "⚖️ Penalties:",
  "1st Infraction — 3-Game QB Suspension",
  "2nd Infraction — Removal from League",
  "🏈 If you start it — you finish it.",
  "\n💪 Part 3 -Sportsmanship & Conduct",
  "Competition drives the league — respect sustains it.",
  "🔥 Code of Conduct:",
  "Trash talk is allowed — it fuels competition.",
  "Personal insults, harassment, or toxicity are not tolerated.",
  "Keep it competitive, not personal.",
  "Respect every opponent, every game.",
  "🏈 Win with class. Lose with dignity.",
  "💬 Part 4 - Communication",
  "Communication ensures consistency and order throughout the league.",
  "📱 League Platforms:",
  "GroupMe — official hub for scheduling, trades, and announcements.",
  "Instagram (@nfl.madden25) — for highlights, awards, and media.",
  "💡 If it’s league-related — it’s on GroupMe.",
  "⏸️ Part 5 — Pause & In-Game Communication",
  "Pauses are a courtesy, not a strategy.",
  "🕹️ Pause Rules:",
  "Allowed for rule alerts or personal reasons.",
  "Communicate clearly when pausing.",
  "Limit: 5 minutes max unless approved.",
  "Excessive or unannounced pauses = strike or penalty.",
  "💬 Transparency builds trust.",
  "📺 Part 6 — Streaming & Game of the Week",
  "Visibility strengthens integrity. Streams validate gameplay and showcase talent.",
  "🎥 Mandatory Streaming:",
  "All Games of the Week and Playoff Games must be streamed.",
  "Approved platforms: YouTube or Twitch.",
  "Players are encouraged to use consistent team-named channels when possible for easy access.",
  "🏆Game of the Week Format",
  "To boost competition and division pride, the league features 4 Games of the Week every advance — 2 AFC and 2 NFC matchups.",
  "All Games of the Week must be streamed on YouTube/Twitch ",
  "📋 Structure:",
  "Commissioners select 4 inter-divisional matchups each advance.",
  "Selections rotate so every team is featured fairly throughout the season.",
  "🏟️ Playoff Streaming Rotation:",
  "Wild Card — Away Team",
  "Divisional — Home Team",
  "Conference — Away Team",
  "Super Bowl — Home Team",
  "🔥 Game of the Week Rewards:",
  "Winners: +2 Attribute Points (<80 OVR)",
  "Division members of the winner: +1 Attribute Point (<80 OVR)",
  "No rewards for SIM or FW games",
  "🏁 Attribute Policy:",
  "Attribute cap: 85 OVR",
  "No SPD, ACC, THP, THA, STR, or PRC boosts",
  "Must post results before advance",
  "🏅 Season Bonus Incentives:",
  "Owners who play 13 or more total games may upgrade one Normal dev player to Star.",
  "The Super Bowl Champion may upgrade one rookie they drafted to Star.",
  "📸 League Media & Highlights:",
  "Players are encouraged to send highlight clips, game-winning plays, or cinematic moments to the Commissioner Team.",
  "Submitted clips may be featured on the official Instagram page — @nfl.madden25 or league highlights feed.",
  "⚖️ Consistency and championship effort are rewarded — not shortcuts.",
  "🤖 Part 7 — CPU Games & Stat Caps",
  "CPU games are for progress, not exploitation.",
  "📊 Limits:",
  "QB — 400 Yards Max",
  "RB — 250 Yards Max",
  "WR/TE — 250 Yards Max",
  "Max 5 CPU attempts ",
  "⚠️ Violations:",
  "Exceeding caps results in a 5 AWR deduction or suspension for involved players.",
  "💰 Part 8 — Salary Cap & Trading Rules",
  "Team management is an art. Rules ensure fair, realistic roster movement.",
  "💰 Salary Cap:",
  "No cutting and re-signing same player.",
  "Player must remain FA until next advance.",
  "Penalty: Player loss + QB –10 AWR.",
  "💼 Trading Rules:",
  "All trades posted in GroupMe and approved by Trade Committee.",
  "No CPU trades.",
  "Both owners must “like” post before approval.",
  "Limit: 6 trades per season (3 Offseason + 3 Regular).",
  "Anti-Collusion: No trades between recruiter and recruit for 2 full seasons.",
  "🧾 Part 9 — Team Lottery & Free Agency System",
  "Competitive balance begins before kickoff.",
  "🎲 Team Lottery (Season 1):",
  "Randomized order determines team selection.",
  "Announced publicly before launch.",
  "💼 Preseason FA Draft:",
  "Week 1 — Reverse of lottery = FA order.",
  "Weeks 2–3 — First-come, first-serve; 2 signings max (1 offense, 1 defense).",
  "After Week 3 — Free agency opens to all.",
  "⚖️ Fair starts lead to fair competition.",
  "🧩 Part 10 — Illegal Subs / Roster Rules / Editing",
  "Rosters must reflect true NFL structure and positions.",
  "⚙️ Illegal Subs:",
  "Offense: ❌ WR→HB/TE | OL→FB/TE",
  "Defense: ❌ SS/FS→CB/LB | CB→SS/FS",
  "Penalty: Strike or removal.",
  "📋 Roster Rules:",
  "42–53 players required",
  "FB optional",
  "Must meet minimums by Week 1",
  "✏️ Editing Policy:",
  "Only allowed in offseason.",
  "Rerolling XP/abilities = dev demotion or game loss.",
  "🧠 Part 11 — Gameplay Conduct",
  "Gameplay should emulate real NFL football — not exploit mechanics.",
  "🏃‍♂️ Motion Rule:",
  "No hiking during motion unless play design permits.",
  "⚡ Speed Burst Rule:",
  "No hand-switching or animation exploits.",
  "🎯 QB Play:",
  "Max dropback: 10 yds (under center), 8 yds (shotgun).",
  "No backward running or drift abuse.",
  "🚨 No Huddle Rule:",
  "Once per drive unless in 2-min or comeback mode.",
  "🛡️ Part 12 — Defense, Goal Line, & 4th Down Rules",
  "Defense wins championships — but only within the rules.",
  "🧱 Defensive Rules:",
  "Minimum 3 rushers (inside tackle box).",
  "No nanos, exploit blitzes, or looping with 3-man rush.",
  "No manual stacking of safeties/LBs to force gaps.",
  "Match personnel — Base vs <3WR; Nickel/Dime vs 3+.",
  "🏈 Goal Line Rules:",
  "Only inside 10-yard line.",
  "Outside 10 — jumbo/short-yardage sets only.",
  "🚦 4th Down Policy:",
  "Inside opponent’s 40 → 4th & 2 or less allowed.",
  "Losing by 14+ → may go for it anywhere.",
  "Inside the half way point  (4th Q) 4 minute mark → free to go for win/tie/cut lead.  up by 9 or more then you must punt, if you’re up by 8 you may go for it ",
  "🎯 2PT Conversions:",
  "Allowed when needed to tie or win.",
  "Losing teams may attempt anytime.",
  "🚨 Penalties:",
  "1st — 1 Suspension",
  "2nd — 5 Suspensions (3 DEF / 2 OFF)",
  "3rd — –3 SPD reduction on starter.",
  "⚡ Part 13-Disconnections",
  "Technical issues happen — sportsmanship must not.",
  "Communicate immediately after disconnects.",
  "Recreate score/time or restart if agreed.",
  "Opponent quits/unplugs → screenshot & send to commissioner.",
  "Playoff disconnects require commissioner approval before restart.",
  "⚖️ Part 14 — League Enforcement (3-Strike System)",
  "Accountability maintains order.",
  "1️⃣ 1st Strike: Warning or 1-Game Suspension",
  "2️⃣ 2nd Strike: 5 Suspensions (3 DEF / 2 OFF)",
  "3️⃣ 3rd Strike: Attribute Reduction (–3 SPD or equivalent)",
  "After 3 strikes, owner review or removal may occur.",
  "All violations documented by commissioners.",
  "✅ Commission Team",
  "Head Commissioner: Fuegobravo",
  "Co-Commissioner: Doughstax",
  "Trade Committee: Onthemaybach + Kadafijones1 ",
  "🩵 Final Message:",
  "This league is for players who respect the game, study their craft, and compete with integrity.",
  "Represent your team, play the right way, and honor the National Franchise League standard.",
  "🤝 League Recruiting:",
  "If you know someone who embodies the values of this league — sportsmanship, discipline, and realism — you are welcome to refer them to the commissioner team for consideration.",
  "Every potential member will be reviewed to ensure they align with the league’s culture and competitive standards.",
  "If a candidate is not selected, please understand — this league maintains a specific vision and style of play, and it’s not for everyone.",
  "⚡ Quality over quantity. The right players make the right league.",
  "🏁 Play smart. Play fair. Have fun.",
];

export function getImportedRuleStatements() {
  return rulebookCategories.flatMap((category) => category.rules.flatMap((rule) => [rule.title, ...rule.content]));
}
